---
title: "Untitled"
output: html_document
date: "2024-11-14"
---


## not sure what to call this yet, a linear model i want to work on 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Linear Models (needs work)
```{r eval=FALSE, include=FALSE}
# Note to future Leah: for mixed linear models: I want to have terms for year, location, and block within location ; this is in addition to having species genotypes and weeds 

model_oatgrain <- aov(oat_yield ~ germplasmName * peaName + pea_yield + studyYear + blockNumber + studyLoc, mulit_location_data)
summary(model_oatgrain)

options(repos = c(CRAN = "https://cran.rstudio.com/"))

library(lme4)

# block within location as a random effect

model_oatgrain <- lmer(oat_yield ~ germplasmName + peaName + pea_yield + studyYear + (1|studyLoc/blockNumber), data = mulit_location_data)
anova(model_oatgrain)
summary(model_oatgrain)

install.packages("lmerTest")
library(lmerTest)
model_oatgrain <- lmer(oat_yield ~ germplasmName * peaName + pea_yield + studyYear + (1|studyLoc/blockNumber), data = mulit_location_data)
anova(model_oatgrain)

# 
model_oat <- lmer(oat_yield ~ germplasmName * peaName * pea_yield * studyLoc * studyYear + (1|studyLoc:blockNumber), data = mulit_location_data)
model_pea <- lmer(pea_yield ~ peaName * germplasmName * oat_yield * studyLoc * studyYear + (1|studyLoc:blockNumber), data = mulit_location_data)

# For model summaries:
summary(model_oat)
summary(model_pea)
anova(model_oat)
anova(model_pea)


# fixed-effect model matrix is rank deficient so checking multicollinearity
library(car)
vif_model <- vif(model_oat)
print(vif_model)


```


